Cosmetics changes

diff --git a/c-cpp/c-cpp-release.yml b/c-cpp/c-cpp-release.yml
--- a/c-cpp/c-cpp-release.yml
+++ b/c-cpp/c-cpp-release.yml
@@ -29,8 +29,11 @@ jobs:
       - name: Configure and build
         run: |
           [ -x ./autogen.sh ] && ./autogen.sh
-          ./configure
-          make
+          [ -x ./configure ] && ./configure
+          [ -s Makefile ] && make || {
+            echo "I couldn't find an autogen.sh, configure, or Makefile."
+            echo "Please check your files."
+          }
       - name: Get properties from configure.ac
         id: props
         # yamllint disable rule:line-length
@@ -84,9 +87,13 @@ jobs:
           fi
       - name: Configure and build
         run: |
+        run: |
           [ -x ./autogen.sh ] && ./autogen.sh
-          ./configure
-          make
+          [ -x ./configure ] && ./configure
+          [ -s Makefile ] && make || {
+            echo "I couldn't find an autogen.sh, configure, or Makefile."
+            echo "Please check your files."
+          }
       - name: Get properties from configure.ac
         id: props
         # yamllint disable rule:line-length
diff --git a/latex/latex-build.yml b/latex/latex-build.yml
--- a/latex/latex-build.yml
+++ b/latex/latex-build.yml
@@ -39,4 +39,6 @@ jobs:
           fi
       - name: Compile LaTeX document
         run: |
-          [ -f Makefile ] && make clean all
+          [ -s Makefile ] && make || {
+            echo "Makefile not found. Please, check your files."
+          }
diff --git a/latex/latex-release.yml b/latex/latex-release.yml
--- a/latex/latex-release.yml
+++ b/latex/latex-release.yml
@@ -34,7 +34,9 @@ jobs:
           fi
       - name: Compile LaTeX document
         run: |
-          [ -f Makefile ] && make clean && make
+          [ -s Makefile ] && make || {
+            echo "Makefile not found. Please, check your files."
+          }
       - name: Upload PDF
         uses: actions/upload-artifact@v4
         with:
