Change '[' for '[[' in many workflows

diff --git a/.github/workflows/c-cpp-build-template.yml b/.github/workflows/c-cpp-build-template.yml
--- a/.github/workflows/c-cpp-build-template.yml
+++ b/.github/workflows/c-cpp-build-template.yml
@@ -49,15 +49,15 @@ jobs:
       - name: Install dependencies
         run: |
           sudo apt-get update
-          if [ -s apt-packages.txt ]; then
+          if [[ -s apt-packages.txt ]]; then
             xargs -a apt-packages.txt sudo apt-get install \
               -y --no-install-recommends
           fi
       - name: Configure and build
         run: |
-          [ -x ./autogen.sh ] && ./autogen.sh
-          [ -x ./configure ] && ./configure
-          [ -s Makefile ] || {
+          [[ -x ./autogen.sh ]] && ./autogen.sh
+          [[ -x ./configure ]] && ./configure
+          [[ -s Makefile ]] || {
             echo "I couldn't find an autogen.sh, configure, or Makefile."
             echo "Please check your files."
             exit 1
@@ -88,14 +88,14 @@ jobs:
           safe_version="$(echo "${VERSION}" | tr -cd '[:alnum:]._-' )"
 
           # Check if variables are empty
-          [ -z "$safe_name" ] && { echo "Invalid name"; exit 1; }
-          [ -z "$safe_version" ] && { echo "Invalid version"; exit 1; }
+          [[ -z "$safe_name" ]] && { echo "Invalid name"; exit 1; }
+          [[ -z "$safe_version" ]] && { echo "Invalid version"; exit 1; }
 
           # Check if files exists
           src="${safe_name}-${safe_version}.tar.gz"
           bin="${safe_name}-${safe_version}-bin.tar.gz"
-          [ -f "$src" ] || { echo "File '${src}' not found"; exit 1; }
-          [ -f "$bin" ] || { echo "File '${bin}' not found"; exit 1; }
+          [[ -f "$src" ]] || { echo "File '${src}' not found"; exit 1; }
+          [[ -f "$bin" ]] || { echo "File '${bin}' not found"; exit 1; }
 
           # Move files
           mkdir -p dist
@@ -113,14 +113,14 @@ jobs:
       - name: Install dependencies
         run: |
           brew update
-          if [ -s brew-packages.txt ]; then
+          if [[ -s brew-packages.txt ]]; then
             xargs brew install < brew-packages.txt
           fi
       - name: Configure and build
         run: |
-          [ -x ./autogen.sh ] && ./autogen.sh
-          [ -x ./configure ] && ./configure
-          [ -s Makefile ] || {
+          [[ -x ./autogen.sh ]] && ./autogen.sh
+          [[ -x ./configure ]] && ./configure
+          [[ -s Makefile ]] || {
             echo "I couldn't find an autogen.sh, configure, or Makefile."
             echo "Please check your files."
             exit 1
@@ -148,12 +148,12 @@ jobs:
           safe_version="$(echo "${VERSION}" | tr -cd '[:alnum:]._-' )"
 
           # Check if variables are empty
-          [ -z "$safe_name" ] && { echo "Invalid name"; exit 1; }
-          [ -z "$safe_version" ] && { echo "Invalid version"; exit 1; }
+          [[ -z "$safe_name" ]] && { echo "Invalid name"; exit 1; }
+          [[ -z "$safe_version" ]] && { echo "Invalid version"; exit 1; }
 
           # Check if file exist
           bin="${safe_name}-${safe_version}-bin.tar.gz"
-          [ -f "$bin" ] || { echo "File '${bin}' not found"; exit 1; }
+          [[ -f "$bin" ]] || { echo "File '${bin}' not found"; exit 1; }
 
           # Move file
           mkdir -p dist
@@ -185,9 +185,9 @@ jobs:
       - name: Configure and build
         shell: msys2 {0}
         run: |
-          [ -x ./autogen.sh ] && ./autogen.sh
-          [ -x ./configure ] && ./configure --host=x86_64-w64-mingw64
-          [ -s Makefile ] || {
+          [[ -x ./autogen.sh ]] && ./autogen.sh
+          [[ -x ./configure ]] && ./configure --host=x86_64-w64-mingw64
+          [[ -s Makefile ]] || {
             echo "I couldn't find an autogen.sh, configure, or Makefile."
             echo "Please check your files."
             exit 1
