Improve sonatype and gpg profiles checking in java central release

diff --git a/.github/workflows/java-central-release-template.yml b/.github/workflows/java-central-release-template.yml
--- a/.github/workflows/java-central-release-template.yml
+++ b/.github/workflows/java-central-release-template.yml
@@ -152,15 +152,10 @@ jobs:
         run: |
           [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1
           [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
-          OUT=$(${mvn} help:all-profiles)
-          if ! echo "$OUT" | grep -q "qulice"; then
-            echo "Error: 'qulice' profile not found in pom.xml or parent"
-            exit 1
-          fi
-          if ! echo "$OUT" | grep -q "gpg"; then
-            echo "Error: 'gpg' profile not found in pom.xml or parent"
-            exit 1
-          fi
+          ${mvn} help:all-profiles | grep -q "sonatype" \
+            || { echo "Error: 'sonatype' profile not found in pom.xml or parent"; exit 1; }
+          ${mvn} help:all-profiles | grep -q "gpg" \
+            || { echo "Error: 'gpg' profile not found in pom.xml or parent"; exit 1; }
           ${mvn} versions:set "-DnewVersion=${{ github.ref_name }}"
           git commit -am "Release ${{ github.ref_name }}"
           ${mvn} deploy -Psonatype -Pgpg --errors --batch-mode
