Check any pom.xml exist in java coverage

diff --git a/.github/workflows/java-coverage.yml b/.github/workflows/java-coverage.yml
--- a/.github/workflows/java-coverage.yml
+++ b/.github/workflows/java-coverage.yml
@@ -13,9 +13,30 @@ defaults:
 permissions:
   contents: read
 jobs:
+  checkcode:
+    runs-on: ubuntu-24.04
+    outputs:
+      proceed: ${{ steps.check.outputs.proceed }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5
+        with:
+          persist-credentials: false
+      - name: Check for code
+        id: check
+        run: |
+          found=$(find . -maxdepth 1 -name "pom.xml")
+          if [ -z "${found}" ]; then
+            echo "Code not found. Stopping execution of the other jobs."
+            echo "proceed=false" >> "${GITHUB_OUTPUT}"
+          else
+            echo "proceed=true" >> "${GITHUB_OUTPUT}"
+          fi
   java-coverage:
     timeout-minutes: 15
     runs-on: ubuntu-24.04
+    needs: checkcode
+    if: needs.checkcode.outputs.proceed == 'true'
     steps:
       - name: Checkout code
         uses: actions/checkout@v5
@@ -25,7 +46,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '21'
       - name: Configure Maven cache
         uses: actions/cache@v4
         with:
@@ -33,4 +54,9 @@ jobs:
           key: ubuntu-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: ubuntu-jdk-21-maven-
       - name: Checks code coverage
-        run: mvn install -Pjacoco
+        # yamllint disable rule:line-length
+        run: |
+          [ -x "mvnw" ] && mvn="./mvnw" || mvn="mvn"
+          profile=$(grep -q "<id>jacoco</id>" pom.xml && echo "-Pjacoco" || echo "")
+          ${mvn} --errors --batch-mode install "${profile}"
+        # yamllint enable rule:line-length
