Check if any pom.xml exist in java sonar

diff --git a/.github/workflows/java-sonar.yml b/.github/workflows/java-sonar.yml
--- a/.github/workflows/java-sonar.yml
+++ b/.github/workflows/java-sonar.yml
@@ -13,9 +13,30 @@ defaults:
 permissions:
   contents: read
 jobs:
+  checkcode:
+    runs-on: ubuntu-24.04
+    outputs:
+      proceed: ${{ steps.check.outputs.proceed }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5
+        with:
+          persist-credentials: false
+      - name: Check for code
+        id: check
+        run: |
+          found=$(find . -maxdepth 1 -name "pom.xml")
+          if [ -z "${found}" ]; then
+            echo "Code not found. Stopping execution of the other jobs."
+            echo "proceed=false" >> "${GITHUB_OUTPUT}"
+          else
+            echo "proceed=true" >> "${GITHUB_OUTPUT}"
+          fi
   java-sonar:
     timeout-minutes: 15
     runs-on: ubuntu-24.04
+    needs: checkcode
+    if: needs.checkcode.outputs.proceed == 'true'
     steps:
       - name: Checkout code
         uses: actions/checkout@v5
@@ -25,7 +46,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 11
+          java-version: '11'
       - name: Configure Maven cache
         uses: actions/cache@v4
         with:
@@ -44,10 +65,10 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         # yamllint disable rule:line-length
         run: |
-          [ -x "mvnw" ] && MVN="./mvnw" || MVN="mvn"
-          PROFILE=$(grep -q "<id>jacoco</id>" pom.xml && echo "-Pjacoco" || echo "")
-          ${MVN} --batch-mode verify "${PROFILE}" -Dinvoker.skip
-          PROFILE=$(grep -q "<id>sonar</id>" pom.xml && echo "-Psonar" || echo "")
-          ${MVN} --batch-mode verify "${PROFILE}" -Dinvoker.skip \
+          [ -x "mvnw" ] && mvn="./mvnw" || mvn="mvn"
+          profile=$(grep -q "<id>jacoco</id>" pom.xml && echo "-Pjacoco" || echo "")
+          ${mvn} --batch-mode verify "${profile}" -Dinvoker.skip
+          profile=$(grep -q "<id>sonar</id>" pom.xml && echo "-Psonar" || echo "")
+          ${mvn} --batch-mode verify "${profile}" -Dinvoker.skip \
             -Dsonar.qualitygate.wait=true
         # yamllint enable rule:line-length
