Checks if qulice and gpg profiles exists in java central release

diff --git a/.github/workflows/java-central-release-template.yml b/.github/workflows/java-central-release-template.yml
--- a/.github/workflows/java-central-release-template.yml
+++ b/.github/workflows/java-central-release-template.yml
@@ -124,6 +124,9 @@ jobs:
         run: |
           [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1
           [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
+          OUT=$(${mvn} help:all-profiles)
+          echo "$OUT" | grep -q "qulice" && echo "$OUT" | grep -q "gpg" \
+            || { echo "Error: 'qulice' and 'gpg' profiles not found in pom.xml"; exit 1; }
           ${mvn} versions:set "-DnewVersion=${{ github.ref_name }}"
           git commit -am "Release ${{ github.ref_name }}"
           ${mvn} clean deploy -Psonatype -Pgpg -Dmaven.test.skip=true --errors --batch-mode
