Fix error if lacheck not found files in latex lint

diff --git a/.github/workflows/latex-lint.yml b/.github/workflows/latex-lint.yml
--- a/.github/workflows/latex-lint.yml
+++ b/.github/workflows/latex-lint.yml
@@ -28,4 +28,4 @@ jobs:
         uses: xu-cheng/texlive-action@8268537fedf1198f3ed7000c544bfdbddcbae3b7
         with:
           scheme: full
-          run: lacheck *.tex
+          run: lacheck *.tex || echo "LaTeX files not found."
